Use cloudflare DNS for session server IP lookup
GlowstoneMC/Glowstone pull request #1010
Opened 2019-01-28 17:20 UTC by heisluft

This PR fixes an issue where the client would be kicked with the message: internal error during login. The server complains about not being able to reach the mojang session server, failing with a timeout exception. This is because netty's ```DefaultDnsServerAddressStreamProvider``` which uses Googles DNS servers (8.8.8.8 and 8.8.4.4) for IP lookup. This PR changes the DNS servers tou cloudflare's (1.1.1.1) thus resolving the issue.

This has been tested many times (it was frustrating to not be able to play on my server for 2 months now) and is proven to solve my issue (Thanks for your fast support on Discord, that really helped :D)

2019-01-28 17:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=1010) <br/>All committers have signed the CLA.

2019-01-28 17:30 UTC, smartboyathome commented
Nice find, but is it possible to use the system's configured DNS server? I don't believe we should be ignoring what is configured in the system. Alternatively, if it's not possible to use the system's configured DNS, we should change these to be configurable rather than hardcoding defaults to a single provider that, for one reason or another, someone may object to.

2019-01-28 17:44 UTC, heisluft commented
Will address that as soon as i got time again (hopefully tomorrow). It seems like ```DefaultDnsServerAddressStreamProvider``` first tries to resolve the systems dns servers and uses google as fallback:
excerpt from  ```DefaultDnsServerAddressStreamProvider```:
```java
 // Using jndi-dns to obtain the default name servers.
        //
        // See:
        // - http://docs.oracle.com/javase/8/docs/technotes/guides/jndi/jndi-dns.html
        // - http://mail.openjdk.java.net/pipermail/net-dev/2017-March/010695.html
        Hashtable<String, String> env = new Hashtable<String, String>();
        env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.dns.DnsContextFactory");
        env.put("java.naming.provider.url", "dns://");
        try {
            DirContext ctx = new InitialDirContext(env);
            String dnsUrls = (String) ctx.getEnvironment().get("java.naming.provider.url");
            // Only try if not empty as otherwise we will produce an exception
            if (dnsUrls != null && !dnsUrls.isEmpty()) {
                String[] servers = dnsUrls.split(" ");
```

2019-01-28 22:10 UTC, mastercoms commented
> These defaults do not respect your host's machines defaults.

[The docs](https://netty.io/4.1/api/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.html) suggest otherwise.

2019-01-28 22:14 UTC, mastercoms requested changes
I would recommend using a `MultiDnsServerAddressStreamProvider` collection of the following:

1. `SequentialDnsServerAddressStreamProvider` initialized from `glowstone.yml` optional user overrides.
2. `UnixResolverDnsServerAddressStreamProvider` to attempt to use the system DNS servers on Linux.
3. `SequentialDnsServerAddressStreamProvider` of `1.1.1.1`, `1.0.0.1`, `8.8.8.8`, `8.8.4.4`.

2019-01-29 14:51 UTC, heisluft commented
Appearantly, I was able to reach the sessionserver both with using cloudflare and google dns servers... The error seems to be the java excerpt I posted above. I looked into the matter and there is literally no way of solving the issue on Window using pure Java. If we decide it to be worth the effort I  _could_ write a C lib and do some JNI magic... However I'm not familiar with Maven at all and don't know how I tell Maven to compile this mess.

2019-03-14 22:44 UTC, mastercoms commented
That can be done later, but for now, I think what I proposed above is fine.

2019-03-17 20:30 UTC, mastercoms commented
Superseded by https://github.com/GlowstoneMC/Glowstone/commit/d486808b2c2f78da5d00aef1f33b90dff4970255.

2019-03-17 20:30 UTC, closed without merging