[BlockLeaves.java] Updated Decay Range
GlowstoneMC/Glowstone pull request #1060
Opened 2019-10-01 01:57 UTC by RabidCodeHog

Updated decay range of leave blocks from 4 to 6 and added variables to allow easier modification of the decay range in the future.

Currently, 'persistent' and 'distance' data has not been changed.

2019-10-03 10:56 UTC, mastercoms commented
Thanks, I'll review this soon. Are you planning to implement the other changes in a new PR?

2019-10-03 19:08 UTC, RabidCodeHog commented
Yep! I'm still pretty new and with school back on I'm going to be taking things a little slower than usual to make sure I don't muck anything up too bad. :)

2019-11-03 15:00 UTC, mastercoms commented on src/main/java/net/glowstone/block/blocktype/BlockLeaves.java
> +    private final byte[] blockMap = new byte[Math.ppw(LEAVE_BLOCK_MAP_RANGE + 2, 3)];
`Math.pow`

2019-11-03 15:03 UTC, mastercoms requested changes
Besides that typo, the change looks fine, though I am concerned about the possibility of collisions in the blockMap.

2020-05-06 12:04 UTC, mastercoms approved these changes
Thank you for your contribution to Glowstone!

2020-05-06 12:05 UTC, merged