[WIP] Ran a Node script to remove the damage property from the recipes.yml.…
GlowstoneMC/Glowstone pull request #1073
Opened 2020-01-14 20:31 UTC by Birbe

Removed the damage property from the recipes with a Node script. This also makes it easier to deal with as in many places we no longer return a map that includes a material along with its damage but simply the material namespaced key alone.

Someone still needs to remove the non-existent blocks from the recipes.

2020-01-14 20:32 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=1073) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=1073) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/Glowstone?pullRequest=1073) it.</sub>

2020-01-14 20:33 UTC, Birbe commented
Building has failed as I haven't updated code to suit the new format.

2020-01-14 20:43 UTC, mastercoms requested changes
This also gets rid of the amount specifier. I wouldn't change the format and instead just remove the damage IDs.

2020-01-14 20:44 UTC, Birbe commented
> 
> 
> This also gets rid of the amount specifier. I wouldn't change the format and instead just remove the damage IDs.

My bad. Will fix.

2020-01-14 22:33 UTC, Birbe commented
I've updated the result.

2020-01-15 17:25 UTC, Birbe commented
The YML parser seemed to have messed up re-serializing some of the arrays and they are now just keyed maps, am fixing.

2020-05-06 16:40 UTC, mastercoms requested changes

2020-05-06 16:40 UTC, mastercoms commented on src/main/java/net/glowstone/inventory/crafting/CraftingManager.java
> +            //float xp = ((Number) data.get("xp")).floatValue(); // NON-NLS
Seems like xp was removed from the original recipes.yml. Is that intentional? If not, could you add it back?

2020-05-06 16:40 UTC, mastercoms commented on src/main/java/net/glowstone/inventory/crafting/CraftingManager.java
> +                    = ItemStack.deserialize((Map<String, Object>) data.get("input")); // NON-NLS;
Remove semicolon here.

2020-08-24 15:47 UTC, closed without merging

2020-08-24 15:48 UTC, mastercoms commented
@Birbe could you possibly send us the Node script under a compatible license for us to continue this work?

2020-08-24 15:56 UTC, Birbe commented
I probably won't be able to find it; I might be able to rewrite it though.

2020-08-24 15:59 UTC, mastercoms commented
Ok, if you could do that, it would be most helpful. Thank you!

2020-12-22 23:30 UTC, Birbe commented
Oof, really sorry to leave you hanging like this. I got the script; I'm cleaning up my computer and I found it, not sure if it's still relevant. 
[rx2j.zip](https://github.com/GlowstoneMC/Glowstone/files/5732379/rx2j.zip)

As for the license:

I donate the attached files and code as a part of the GlowstoneMC project, you may use it however you'd like.

2020-12-22 23:39 UTC, mastercoms commented
Thanks so much!