Added some missing tags to ArrowStore and ProjectileStore and added the new Int-Array representation of UUIDs to CompoundTag
GlowstoneMC/Glowstone pull request #1115
Opened 2021-07-09 17:18 UTC by VaiTon

feat: added missing tags to ArrowStore and ProjectileStore
feat: added new Int-Array representation of UUIDs in CompoundTag

2021-07-14 20:50 UTC, mastercoms requested changes

2021-07-14 20:50 UTC, mastercoms commented on src/main/java/net/glowstone/util/nbt/CompoundTag.java
> +     * <p>
use `<br>` or close the `<p>` tag.

2021-07-15 11:09 UTC, VaiTon commented
I'm reopening this with some more :)

2021-07-16 20:00 UTC, mastercoms approved these changes

2021-07-16 20:00 UTC, merged