Utilize RecipeManager and TagManager from Redstone Transformer
GlowstoneMC/Glowstone pull request #1116
Opened 2021-07-11 05:43 UTC by smartboyathome

This PR swaps out the tags and recipe manager implementations for their counterparts from the redstone transformer. This allows us to get this data from the default datapack easily without keeping that data around and without having to hardcode these recipes. The implementations differ slightly from their Glowstone counterparts, but usually only in name. We may want to switch away from using the MaterialSetTag class to our own wrapper around SubTagTrackingTag in order to allow for modifications to these custom tags to be tracked in the future.

2021-07-11 19:47 UTC, mastercoms requested changes

2021-07-11 19:47 UTC, mastercoms commented on src/main/java/net/glowstone/inventory/crafting/CraftingManager.java
> -        InputStream in = getClass().getClassLoader().getResourceAsStream("builtin/recipes.yml");
We can delete this file.

2021-07-11 19:49 UTC, mastercoms commented
Also, I am not sure how relevant `materialValues.yml` and `fishingRewards.yml` will be once Redstone Transformer is done, but if they will still be relevant, could you add tag support to both of them?

2021-07-13 16:45 UTC, smartboyathome commented
materialValues.yml currently doesn't have an equivalent in the Redstone Transformer. The data this file contains isn't available from Mojang itself through data packs, but it looks like it is available in [PrismarineJS's minecraft-data](https://github.com/PrismarineJS/minecraft-data).

For fishingRewards.yml, this should eventually be replaced by the fishing loot table in Mojang's official data pack.

2021-07-14 20:46 UTC, mastercoms commented
@smartboyathome Could you resolve merge conflicts? Should be good after that.

2021-07-14 20:46 UTC, mastercoms approved these changes

2021-07-14 21:37 UTC, merged