ref: use default GlowKit BoundingBox & nullability annotations
GlowstoneMC/Glowstone pull request #1131
Opened 2021-12-12 01:18 UTC by VaiTon

1. Use the default GlowKit/Bukkit implementation of BoundingBox instead of using a custom one.
2. Added some more nullability annotations.

2021-12-12 16:51 UTC, mastercoms requested changes
Everything else looks good to me, though I'll have to do a second pass later

2021-12-12 16:51 UTC, mastercoms commented on src/main/java/net/glowstone/GlowWorld.java
> +import net.glowstone.constants.*;
No wildcard imports.

2022-02-12 03:40 UTC, mastercoms requested changes
Are the java. import ordering changes correct?

2022-06-14 15:30 UTC, VaiTon commented
@mastercoms they should be as I'm using checkstyle. I'm merging the conflicts!

2024-11-06 19:56 UTC, closed without merging