[WIP] Block break stages
GlowstoneMC/Glowstone pull request #473
Opened 2017-05-14 23:17 UTC by satoshinm

- [x] Add block break animation message and codec
- [ ] Calculate block break stage when breaking
- [ ] Broadcast message to nearby clients
- BlockCrackEvent API event? (fire in between BlockDamageEvent and BlockBreakEvent)

2017-05-14 23:22 UTC, satoshinm commented
Added the 0x08 codec, but that's the easy part, I'll have to dig into the code further to see how to send this message to nearby clients appropriately (or if anyone wants to lend me some pointers how this would be done?). Note this message allows clients to see the block break stages when other players are digging blocks.

2017-05-15 23:24 UTC, momothereal commented
You can use something like [this](https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/block/entity/BlockEntity.java#L43) to update in range.

2017-05-16 01:14 UTC, aramperes requested changes

2017-05-16 01:14 UTC, momothereal commented on src/main/java/net/glowstone/net/message/play/game/BlockBreakAnimationMessage.java
> +    private final int entityID, x, y, z, destroyStage;
For the sake of continuity with other entity Message classes, change `entityID` to `id`.

2017-05-16 01:14 UTC, momothereal commented on src/main/java/net/glowstone/net/codec/play/game/BlockBreakAnimationCodec.java
> +
Extra whitespace.

2017-05-16 03:10 UTC, mastercoms commented on src/main/java/net/glowstone/net/codec/play/game/BlockBreakAnimationCodec.java
> +
Is that not a newline at the end of file?

2017-05-16 03:11 UTC, mastercoms requested changes

2017-05-16 03:11 UTC, mastercoms commented on src/main/java/net/glowstone/net/message/play/game/BlockBreakAnimationMessage.java
> +}
Add a newline here please.

2017-05-16 04:04 UTC, satoshinm commented on src/main/java/net/glowstone/net/codec/play/game/BlockBreakAnimationCodec.java
> +
It's an extra newline, I'll remove it

2017-05-16 04:10 UTC, mastercoms commented
Ah, I thought GitHub was supposed to show newlines.

2017-05-16 04:44 UTC, satoshinm commented
Added an initial block break animation

2017-05-16 04:47 UTC, satoshinm commented
<img width="966" alt="screen shot 2017-05-15 at 9 44 07 pm" src="https://cloud.githubusercontent.com/assets/26856618/26090134/c11a8204-39b7-11e7-8d15-fd2a505bf6da.png">

Added an initial block break animation broadcast, other clients can now see the initial block break stage. However, the digging handler isn't continuously called, only when digging starts/stops. I think to implement this properly, the server would need to know each blocks' hardness to calculate the stages, then increment accordingly. Looking at another open source server (Cuberite) it seems they haven't implemented this part yet either: https://github.com/cuberite/cuberite/blob/01d9beee9ee60aa1ead52f7796c762a8372b9ca4/src/ClientHandle.cpp#L1223-L1231 "TODO: Send animation packets even without receiving any other packets"

2017-05-16 04:54 UTC, mastercoms commented
Yeah but I don't think it is good to have it in a client tick. Digging is caused by the packet, and so any tasks should off shoot from there. 

About hardness, that info is stored in the material values collection.

2017-05-17 03:48 UTC, satoshinm commented
> Yeah but I don't think it is good to have it in a client tick. Digging is caused by the packet, and so any tasks should off shoot from there.

Start an asynchronous task if `message.getState() == DiggingMessage.START_DIGGING`, sending increasingly block break destroy stage packets at an interval, then cancel the task when the block breaks or digging stops (`message.getState() == DiggingMessage.FINISH_DIGGING`)?

[materialValues.yml](https://github.com/GlowstoneMC/Glowstone/blob/77e30f78e4e323ae61a999c7dad3075731985f77/src/main/resources/builtin/materialValues.yml) has a `hardness` field but only values used are: 1 (default), -1 (bedrock), 0 (soft blocks, plants etc.), and 50 (bedrock).

Hardness values to populate the yaml can be found at: http://minecraft.gamepedia.com/Breaking#Blocks_by_hardness

2017-05-17 03:51 UTC, mastercoms commented
This PR would probably depend on [#379](https://github.com/GlowstoneMC/Glowstone/pull/379/files#diff-9f83ce130d9b3bff618cb81945f17116R14).

About the async task, I think it could work like that.

2017-05-17 04:12 UTC, satoshinm commented
Hm, didn't see https://github.com/GlowstoneMC/Glowstone/pull/379/files#diff-9f83ce130d9b3bff618cb81945f17116R14 .. are the hardnesses moving to BuiltinMaterialValueManager.java out of materialValues.yml? Went ahead and added to .yml before I saw this, http://minecraft.gamepedia.com/Breaking#Blocks_by_hardness has all the hardness values for reference except skulls but http://minecraft.gamepedia.com/Mob_head says skull hardness = 1.

2017-05-17 04:13 UTC, mastercoms commented
Yeah they're being moved to the class so it can better support custom materials and programmable modifications of vanilla materials.

2017-05-22 02:54 UTC, satoshinm commented on src/main/java/net/glowstone/net/message/play/game/BlockBreakAnimationMessage.java
> +}
Added newline after the variable declarations

2017-05-22 03:03 UTC, satoshinm commented on src/main/java/net/glowstone/net/message/play/game/BlockBreakAnimationMessage.java
> +    private final int entityID, x, y, z, destroyStage;
Changed to id

2017-05-22 03:16 UTC, satoshinm commented
Addressed the requested changes but they still show as changes requested, how can I mark them addressed?

Implemented the block break animation stages, used player pulse() seemed to make the most sense there. Added cancel digging support. This is functional now however, I'm finding the hardness differs from what the player sees:

<img width="1560" alt="screen shot 2017-05-21 at 8 06 07 pm" src="https://cloud.githubusercontent.com/assets/26856618/26291130/17cad768-3e61-11e7-8cd3-97072a8017a2.png">

left = the player digging, right = the block break animation from another client (too fast).

It isn't taking into account the tool/effectiveness versus hardness. From http://minecraft.gamepedia.com/Breaking#Blocks_by_hardness - stone "hardness" is 1.5 seconds, but when mined with a bare hand it is 7.5 seconds. The equation is described in http://minecraft.gamepedia.com/Breaking#Speed:

> The base time in seconds is the block's hardness multiplied by 1.5 if the player can harvest the block with the current tool, or multiplied by 5 if the player cannot.

2017-05-22 03:19 UTC, mastercoms commented
The reviewer has to approve changes. Nothing you need to do.

Due to the complexity of this issue, I believe it is best to leave it for another PR. Initial block break animation support is sufficient, in my opinion.

2017-05-22 03:19 UTC, mastercoms approved these changes

2017-05-22 03:40 UTC, satoshinm commented
Agreed, sounds good. I changed it for now to use the correct hardness for if the block is mined with bare hands and is not dropped, for example, hands on stone -- the animations now match. The consequences of incorrect block break animation are purely cosmetic, tool effectiveness can be factored in later, I think this is good enough for now.

2017-05-22 03:44 UTC, momothereal commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        long duration = System.currentTimeMillis() - diggingStarted;
Wouldn't it be better to base this system off world thread ticking, instead of system time in milliseconds?

2017-05-22 05:08 UTC, satoshinm commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        long duration = System.currentTimeMillis() - diggingStarted;
Good point, will fix

2017-05-22 15:10 UTC, aramperes approved these changes

2017-05-22 15:59 UTC, mastercoms requested changes

2017-05-22 15:59 UTC, mastercoms commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        if (block == null) return;
Wouldn't this work better as a precondition?

2017-05-22 15:59 UTC, mastercoms commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        block.getWorld().getRawPlayers().stream().filter(player1 -> player1.canSeeChunk(key)).forEach(player2 -> {
Could you explain to me what this code is doing?

2017-05-22 17:02 UTC, satoshinm commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        if (block == null) return;
Agreed, changed to move the check outside the function - it should only be called with non-null block now

2017-05-22 17:07 UTC, satoshinm commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        block.getWorld().getRawPlayers().stream().filter(player1 -> player1.canSeeChunk(key)).forEach(player2 -> {
It is getting the chunk of the block and filtering the list of players to those who can see the chunk, so it only sends the block breaking animation to the right players. I wasn't familiar with the Streams API and Java lambdas but it seems to be a common pattern in Glowstone:

```
src/main/java/net/glowstone/block/entity/BlockEntity.java
45:        block.getWorld().getRawPlayers().stream().filter(player -> player.canSeeChunk(key)).forEach(this::update);

src/main/java/net/glowstone/block/state/GlowNoteBlock.java
189:        getWorld().getRawPlayers().stream().filter(player -> player.canSeeChunk(key)).forEach(player -> player.playNote(location, instrument, note));

src/main/java/net/glowstone/entity/GlowEntity.java
1024:        world.getRawPlayers().stream().filter(player -> player.canSeeEntity(this)).forEach(player -> player.getSession().send(message));

src/main/java/net/glowstone/entity/objects/GlowItem.java
71:            world.getRawPlayers().stream().filter(other -> other.canSeeEntity(this)).forEach(other -> other.getSession().send(message));
```

but the players are filtered twice for chunk visibility, both here and in sendBlockBreakAnimation:

```java
    public void sendBlockBreakAnimation(BlockBreakAnimationMessage message) {
        // only send message if the chunk is within visible range
        Key key = new Key(message.getX() >> 4, message.getZ() >> 4);
        if (canSeeChunk(key)) {
            afterBlockChanges.add(message);
        }
    }
```

leaning towards removing this second check and only performing the filtering in broadcastBlockBreakAnimation

2017-05-22 18:39 UTC, mastercoms requested changes

2017-05-22 18:39 UTC, mastercoms commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        block.getWorld().getRawPlayers().stream().filter(player1 -> player1.canSeeChunk(key)).forEach(player2 -> {
Ok. Why did you name your variables player1 and player2? Can't they both be player?

Also you have an if statement within the for-each lambda that could be part of the filter predicate.

2017-05-25 22:22 UTC, mastercoms commented
@satoshinm GitHub is wrongly hiding my comment here: https://github.com/GlowstoneMC/Glowstone/pull/473#discussion_r117816322

I'm not sure if you saw it because of this.

2017-05-26 01:34 UTC, satoshinm commented
@mastercoms thanks didn't see it, will fix

2017-05-26 01:35 UTC, satoshinm commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +        block.getWorld().getRawPlayers().stream().filter(player1 -> player1.canSeeChunk(key)).forEach(player2 -> {
Made both changes, also removed unnecessary Player parameter

2017-05-26 02:59 UTC, mastercoms approved these changes

2017-05-26 03:00 UTC, mastercoms commented
Alright, looks good. Thank you for your contribution to Glowstone.

2017-05-26 03:00 UTC, merged

2017-05-26 03:01 UTC, mastercoms commented
By the way, did you see our invite at https://github.com/GlowstoneMC?