Use IdleStateHandler for both ReadTimeoutHandler and WriteTimeoutHandler
GlowstoneMC/Glowstone pull request #480
Opened 2017-05-27 06:26 UTC by louxiu

`IdleStateHandler` has the function of `ReadTimeoutHandler`. So no extra `ReadTimeoutHandler` is needed

2017-05-27 15:40 UTC, mastercoms requested changes
Thank you for your contribution to Glowstone! This PR looks good to me, but I think while we're modifying this, we can also move the idle state handler up to be the first one added to the pipeline.

2017-05-28 02:58 UTC, louxiu commented
@mastercoms That make sense. Updated

2017-05-28 03:18 UTC, mastercoms approved these changes

2017-05-28 03:19 UTC, mastercoms commented
Alright, thank you for your contribution to Glowstone.

2017-05-28 03:19 UTC, merged