Add me, seed, xp and defaultgamemode commands
GlowstoneMC/Glowstone pull request #521
Opened 2017-07-07 21:09 UTC by FlorentClarret

Hi,

This PR relates to this issue : https://github.com/GlowstoneMC/Glowstone/issues/499. It implements the following vanilla commands : 
- me
- seed
- defaultgamemode
- xp

2017-07-07 21:29 UTC, kamcio96 commented
`/me` the most useless command ever

2017-07-08 03:17 UTC, aramperes requested changes

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/XpCommand.java
> +                    sender.sendMessage(ChatColor.RED + "Unknown or offline player.");
Replace this with `Player 'name' cannot be found`

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/XpCommand.java
> +                    sender.sendMessage(ChatColor.RED + "Cannot give negative experience.");
Replace this with `Cannot give player negative experience points`

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/XpCommand.java
> +                    sender.sendMessage(ChatColor.RED + "Cannot give levels: invalid number format.");
Replace this error (and the one below it) with `'number' is not a valid number`

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/SeedCommand.java
> +            sender.sendMessage(ChatColor.RED + "Can not get the world");
No need to send this error, just return false. It would never happen to a block/entity/console.

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/SeedCommand.java
> +    public boolean execute(CommandSender sender, String label, String[] args) {
Needs a permission check here.

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/MeCommand.java
> +    public boolean execute(CommandSender sender, String label, String[] args) {
Needs a permission check here.

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/DefaultGameModeCommand.java
> +    private static final List<String> GAMEMODES = Arrays.asList("adventure", "creative", "survival", "spectator");
Declare this array in CommandUtils, and use it for both `/gamemode` and `/defaultcommand`. Also, make it an unmodifiable list.

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/DefaultGameModeCommand.java
> +            sender.sendMessage(ChatColor.RED + "Missing arguments. Usage: " + usageMessage);
Remove the "Missing arguments." part.

2017-07-08 03:17 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/DefaultGameModeCommand.java
> +        sender.sendMessage("Default game mode set to " + ChatColor.GRAY + "" + ChatColor.ITALIC + gamemode.toString().toLowerCase());
Replace this message with `The world's default game mode is now <Gamemode> Mode` (uppercase for first letter of <Gamemode>)

2017-07-08 05:51 UTC, FlorentClarret commented
I created a new class to hold the gamemodes, to convert a string to the enum and also to prettyPrint the name of the enum instead of adding everything in the CommandUtils class.

2017-07-08 05:55 UTC, aramperes approved these changes
Looks good! Kudos for making a unit test.

2017-07-08 05:56 UTC, merged

2017-07-08 05:56 UTC, momothereal commented
Thank you for your contribution!