Support multiple passengers
GlowstoneMC/Glowstone pull request #524
Opened 2017-07-09 18:13 UTC by Postremus

This PR attempts to implement multiple passengers per vehicle.

Save and load Passengers. When an entity is a passenger, it will only be saved as child of its vehicle, and never alone.
Adjust api implementation to be (hopefully) in line with papers.
Also set the size for armorstands and horses.

closes #522
related to #504

2017-07-11 23:06 UTC, aramperes requested changes

2017-07-11 23:06 UTC, aramperes commented on src/main/java/net/glowstone/entity/GlowEntity.java
> +        Preconditions.checkArgument(passenger != this, "Entity cannot ride itself.");
Replace `passenger != this` with `!Objects.equals(passenger, this)`

2017-07-11 23:06 UTC, aramperes commented on src/main/java/net/glowstone/entity/GlowEntity.java
> +        Preconditions.checkArgument(passenger != this, "Entity cannot ride itself.");
See previous review comment (don't use `!=`/`==` for equality checks)

2017-07-11 23:06 UTC, momothereal commented on src/main/java/net/glowstone/entity/GlowEntity.java
> +        glowPassenger.teleport(onTopOfVehicle);
I think you would also need to teleport the passenger after dismounting, no?

2017-07-11 23:06 UTC, momothereal commented on src/main/java/net/glowstone/io/entity/EntityStore.java
> +                    entity.addPassenger(passenger);
Perhaps you should make another ("internal") method when setting the passengers from NBT -- you wouldn't want to fire these events when loading the world.

2017-07-12 15:59 UTC, Postremus commented on src/main/java/net/glowstone/io/entity/EntityStore.java
> +                    entity.addPassenger(passenger);
I have to agree with you, that normally you would not want to fire these events during world load.  
Spigot however does throw them during world load..

2017-07-12 16:43 UTC, momothereal commented on src/main/java/net/glowstone/io/entity/EntityStore.java
> +                    entity.addPassenger(passenger);
Ah okay, that's fine then.

2017-07-12 22:14 UTC, aramperes requested changes

2017-07-12 22:14 UTC, momothereal commented on src/main/java/net/glowstone/entity/GlowEntity.java
> +        // apply location changes to all passengers
Empty comment block? Or is there something missing here?

2017-07-12 22:14 UTC, momothereal commented on src/main/java/net/glowstone/io/entity/EntityStore.java
> +            GlowServer.logger.warning("Skipping Entity with id " + id);
Log the exception here

2017-07-13 23:08 UTC, aramperes requested changes

2017-07-13 23:08 UTC, momothereal commented on src/main/java/net/glowstone/entity/GlowEntity.java
> +    private List<Entity> passengers = new ArrayList<>();
This field can be final (and perhaps `protected` too)

2017-07-15 01:20 UTC, aramperes approved these changes

2017-07-15 01:21 UTC, merged