[WIP] #526 and # 525 - Fix shift click when crafting and refresh the crafting result slot
GlowstoneMC/Glowstone pull request #527
Opened 2017-07-13 22:55 UTC by FlorentClarret

Hi,

This PR relates the following issues :

- https://github.com/GlowstoneMC/Glowstone/issues/525
- https://github.com/GlowstoneMC/Glowstone/issues/526

The crafting result slot is now updated if a new item can be crafted. Also, I fixed the shift click on crafting as well. 

There is still one little thing I need to fix : when shift clicking, the amount of layers is first reduced by 1 and right after completely reset. The result is correct, all the items are crafted and the required items removed, but the layers are supposed to be removed all at once.

2017-07-14 06:11 UTC, FlorentClarret commented
For some reason, when shift clicking, a single click seems to be performed on the client side before the server get the shift click. This is where the - 1 on the layers comes from. On debug mode, i didn't manage to catch this "single click" before the shift click, and the shift click is working properly.

Do you have any idea where this comes from ?

2017-07-16 06:30 UTC, FlorentClarret commented
I didn't manage to find out why we have this first layer removed on the client side before the server remove all the layers. However, this PR closes the two issues so if it's ok for you we could merge it.

If you have any idea why we have this, feel free to tell me :)

2017-07-22 15:44 UTC, aramperes requested changes

2017-07-22 15:44 UTC, momothereal commented on src/main/java/net/glowstone/inventory/GlowCraftingInventory.java
> +            CraftingManager cm = ((GlowServer) Bukkit.getServer()).getCraftingManager();
You can use `player.getServer()` which returns `GlowServer`

2017-07-22 15:44 UTC, momothereal commented on src/main/java/net/glowstone/inventory/crafting/CraftingManager.java
> +            if (item != null && item.getAmount() != 0 && (item.getAmount() < layers || layers == 0)) {
Use `!InventoryUtil.isEmpty(item)` instead of amount/null check

2017-07-23 00:13 UTC, aramperes approved these changes

2017-07-23 00:14 UTC, merged

2017-07-23 00:17 UTC, momothereal commented
Thank you for your contributions :)

The layer-removing glitch is very minor, but you can feel free to open an issue about it.