Clean-up unnecessary comments and sout
GlowstoneMC/Glowstone pull request #533
Opened 2017-07-26 12:56 UTC by louxiu

1.Interface has comments already, so the comments in implements is
unnecessary
2. Replace sout with log

2017-07-26 12:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=533) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=533) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/Glowstone?pullRequest=533) it.</sub>

2017-07-26 16:10 UTC, aramperes requested changes

2017-07-26 16:10 UTC, momothereal commented on src/main/java/net/glowstone/net/handler/play/player/AdvancementTabHandler.java
> +            GlowServer.logger.log(Level.SEVERE, "Received AdvancementTabHandler (close)");
`Level.DEBUG`/`Level.INFO` perhaps?

2017-07-27 01:05 UTC, louxiu commented
@momothereal Oh, I didn't comprehend the `Level` correctly. I think `DEBUG`(Level.FINE?) is suitable.

2017-07-27 01:05 UTC, louxiu commented on src/main/java/net/glowstone/net/handler/play/player/AdvancementTabHandler.java
> +            GlowServer.logger.log(Level.SEVERE, "Received AdvancementTabHandler (close)");
done

2017-07-27 11:47 UTC, aramperes approved these changes

2017-07-27 11:47 UTC, merged