Use map instead of list for CommandFunction
GlowstoneMC/Glowstone pull request #537
Opened 2017-08-06 04:26 UTC by louxiu

2017-08-06 14:32 UTC, aramperes requested changes

2017-08-06 14:32 UTC, momothereal commented on src/main/java/net/glowstone/command/minecraft/FunctionCommand.java
>          if (function == null) {
Use `getFunctions().containsKey()` check here, and `get` the function after that check.

2017-08-07 01:41 UTC, louxiu commented
@momothereal done

2017-08-07 13:16 UTC, aramperes approved these changes
Looks good! Please avoid re-writing commits/history though, splitting in multiple commits is easier for reviewing changes - we squash everything when merging anyways :)

2017-08-07 13:16 UTC, merged

2017-08-08 02:08 UTC, louxiu commented
@momothereal ok