Fix #584 - ConcurrentModificationException
GlowstoneMC/Glowstone pull request #585
Opened 2017-11-01 15:48 UTC by Microsamp

We should use a CopyOnWriteArrayList to prevent ConcurrentModificationExceptions, while iterating and removing/adding some elements to the list.

Ps: I tried to implement/test ReadWriteLocks, but the performance and stability(deadlocks etc.) wasn't that great.

 https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html

2017-11-01 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=585) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/Glowstone?pullRequest=585) it.</sub>

2017-11-01 23:05 UTC, momothereal commented
Hello @Microsamp,

Thank you for your contribution. Please make sure you sign the Contributor License Agreement before we review your pull request. See the comment left by the CLA assistant bot above.

2017-11-01 23:08 UTC, Microsamp commented
Hello @momothereal,

i signed the Contributor License Agreement.

2017-11-02 13:36 UTC, momothereal commented
I'm worried about the possible performance hit this would cause. Keep in mind that each entity has a Task Manager being pulsed every tick, and this solution appears to be quite costly according to the docs.

2017-11-02 13:52 UTC, momothereal commented
What about using `ConcurrentSkipListSet`? From what I understand, it is safely iterable, but it may happen that a task won't be pulsed until the next tick after it is added.

2017-11-02 14:55 UTC, Microsamp commented
> What about using ConcurrentSkipListSet?
Mhmmm, it seems to be a better choice for performance.

> but it may happen that a task won't be pulsed until the next tick after it is added.
I think it doesn't matter if a task is executed one tick later.

2017-11-02 15:07 UTC, Microsamp commented
WIP

2017-11-02 15:53 UTC, momothereal commented
I guess we could use the Comparable class to prioritize tasks (ordering), but that it is probably out of the scope of this PR.

2017-11-02 15:58 UTC, Microsamp commented
The question is: Should i fix the exception with the first commit, should i prioritize all EntityTasks with 0 or should i wait for a full concept of your idea

2017-11-02 15:59 UTC, aramperes commented
If it is outside of the scope, you can put a placeholder to fix the exception (for instance, using 0 for the Comparable impl), as long as it kinda works.

2017-11-02 18:22 UTC, Microsamp commented
So: I implemented your workaround with ConcurrentSkipListSet and default priority(comparable#compareTo) of zero.

I spawned many zombies(20-30) and hitted them. The zombies moved around and died(diamond-sword) after 2 or 3 punches.
After killing all zombies the thread number(/glowstone) is now 18(normal).

2017-11-03 14:40 UTC, aramperes requested changes

2017-11-03 14:40 UTC, momothereal commented on src/main/java/net/glowstone/entity/ai/EntityTask.java
> +        return 0;
Add a todo here (`// todo: AI task priority`)

2017-11-22 17:33 UTC, aramperes approved these changes

2017-11-23 05:32 UTC, merged

2017-11-23 05:34 UTC, momothereal commented
Thank you for your contribution!