Fix fire not getting updated. Fixes #435
GlowstoneMC/Glowstone pull request #589
Opened 2017-11-24 20:57 UTC by kumpelblase2

After causing a fire through flint and steel, fire did not behave properly: it just sat there doing nothing. The reason for this behavior was due to setting the type to the material the player was currently holding. Since it was flint and steel, it was set to that instead of a fire block. Running an update on that obviously does nothing.

Setting the block type to fire on the other hand does the right thing. Updates get propagated, it will spread and at some point stop.

The fire spreading seems to be a little off as well, but I left that for another day.

2017-11-24 20:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=589) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=589) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/Glowstone?pullRequest=589) it.</sub>

2017-11-24 21:05 UTC, mastercoms approved these changes

2017-11-25 02:58 UTC, mastercoms reviewed
I'm not sure that is this is the right fix, since fire ticking was working before a few tick system updates. I'd rather try to find the root of the issue rather than workaround it.

However, maybe this is a good fix, at least for now. I'll have to investigate it further though.

Regardless, thank you for your contribution!

2017-11-25 09:59 UTC, aramperes approved these changes

2017-11-25 16:50 UTC, kumpelblase2 commented
The reason it currently didn't run the update is the following. After right clicking, the block location got scheduled for receiving ticks and the type of the block was set to what the player was holding (which is wrong in this case). Once the next tick comes in, we reach `GlowWorld#pulseTickMap`, spicifically https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/GlowWorld.java#L1951 . `getMaterial` here returns "Flint & Steel", which is wrong (and this PR fixes that). Because it returns that instead of "Fire", the `itemTable.getBlock` returns null as "Flint & Steel" has no block type (which is correct). Since there's no block type for this location the system just thinks there's nothing here and stops progressing ticks for that location.

I didn't run this with fire created by the environment, which might still work without this fix. But fire created by flint and steel certainly didn't.

So I do acutally believe the system behaved correctly, given that we somewhat fed it wrong info. That it worked before seems to be more of a coincidence in this case. And therefor I wouldn't consider this a workaround but rather the correct fix here.

2017-11-25 17:24 UTC, mastercoms commented
If that's issue, I think the fix should be setting flint and steel's placeAs to fire.

2017-11-25 20:35 UTC, momothereal commented
Can confirm that overriding ItemFlintAndSteel's `placeAs` to BlockFire resolves this problem.

2017-11-25 20:36 UTC, aramperes requested changes
See comment.

2017-11-25 23:34 UTC, kumpelblase2 commented
Alright, that does sound like a better solution. Updated PR accordingly.

2017-11-25 23:41 UTC, aramperes approved these changes

2017-11-25 23:42 UTC, merged

2017-11-25 23:42 UTC, mastercoms commented
Thank you very much for your contribution to Glowstone!