Add log4j configuration
GlowstoneMC/Glowstone pull request #629
Opened 2017-12-20 08:13 UTC by Pr0methean

Necessary to fix a warning at startup.

2017-12-20 17:13 UTC, smartboyathome requested changes

2017-12-20 17:13 UTC, smartboyathome commented on src/main/resources/log4j.xml
> +        <priority value ="debug" />
Since this is the "release" config, we probably should have the priority set to info.

2017-12-20 17:14 UTC, smartboyathome commented
Also, in general, I think it would be more useful if log4j output were logged to a file rather than to the console.

2017-12-20 19:52 UTC, aramperes requested changes

2017-12-20 19:52 UTC, momothereal commented on src/main/resources/log4j.xml
> +</log4j:configuration>
Add a blank line at the end (LF) for both files.

2017-12-20 20:10 UTC, Pr0methean commented
I think it's an important feature of Minecraft that errors and warnings are available on the console, even with the more stable Mojang code, so I've set the production log4j.xml to handle messages like so:

- Warning or error: file and console
- Info: file only
- Debug: ignore

2017-12-20 20:35 UTC, smartboyathome approved these changes

2017-12-20 23:16 UTC, aramperes approved these changes

2017-12-21 02:56 UTC, mastercoms approved these changes

2017-12-21 02:56 UTC, merged