Added testforblocks command, along with unit tests
GlowstoneMC/Glowstone pull request #658
Opened 2017-12-31 05:37 UTC by smartboyathome

Needed to refactor the GlowChunk object out of BlockType.createBlockEntity() in order to make it easier to mock the GlowBlocks without touching GlowChunk.

2017-12-31 09:38 UTC, Pr0methean commented on src/test/java/net/glowstone/testutils/InMemoryBlockStorage.java
> +        GlowBlock mockBlock = PowerMockito.mock(GlowBlock.class);
I think you can use plain Mockito here, since the class is no longer final.

2017-12-31 18:47 UTC, mastercoms requested changes
You're doing a getBlock call even if there is no block entity to be created.

2018-01-02 04:19 UTC, smartboyathome commented
I didn't see anything wrong with this since GlowBlock is little more than a thin wrapper that points back to GlowChunk, and this only happens when a block's type is changed. Don't think lambda is going to be much better here, though, so I'll revert the changes to blocktypes though and just mock the getBlock function in GlowChunk.

2018-01-07 18:12 UTC, mastercoms approved these changes

2018-01-07 18:13 UTC, merged