Allow customization of libraries by server operators.
GlowstoneMC/Glowstone pull request #808
Opened 2018-01-08 23:49 UTC by smartboyathome

This allows server operators to manually specify libraries that their plugins need to run. Phase one of #451.

2018-01-09 00:59 UTC, mastercoms commented on src/main/java/net/glowstone/util/Library.java
> +package net.glowstone.util;
Perhaps move these into a new package?

2018-01-09 04:42 UTC, mastercoms commented on src/main/java/net/glowstone/GlowServer.java
> +import net.glowstone.library.LibraryManager;
Sorry that I wasn't clear, I meant net.glowstone.util.library, but I'm fine with this too. It's really up to you with which you feel is better.

2018-01-10 04:42 UTC, aramperes requested changes

2018-01-10 04:42 UTC, momothereal commented on src/main/java/net/glowstone/util/ClassPathAgent.java
> +    public static void addJarFile(JarFile file) {
Needs documentation

2018-01-10 04:42 UTC, momothereal commented on src/main/java/net/glowstone/util/config/ServerConfig.java
> +     * @param key the key to look up
Blank line before description and params

2018-01-10 04:42 UTC, momothereal commented on src/main/java/net/glowstone/util/library/Library.java
> +    public static Library fromConfigMap(Map<?, ?> configMap) {
Needs documentation

2018-01-10 04:42 UTC, momothereal commented on src/main/java/net/glowstone/util/library/Library.java
> +    public String getGroupId() {
Lombokify these getters

2018-01-10 04:42 UTC, momothereal commented on src/main/java/net/glowstone/util/library/Library.java
> +    public Map<?, ?> toConfigMap() {
Needs documentation

2018-01-13 16:55 UTC, aramperes requested changes

2018-01-13 16:55 UTC, momothereal commented on src/main/java/net/glowstone/util/ClassPathAgent.java
> +     * @param file The JAR file to add to the class loader.
Line between the description and params

2018-01-13 18:15 UTC, aramperes requested changes

2018-01-13 18:15 UTC, momothereal commented on src/main/java/net/glowstone/util/library/LibraryManager.java
> +         * @param library the library containing the algorithm and the checksum.
`the {@link Library} containing [...]`

2018-01-13 18:15 UTC, momothereal commented on src/main/java/net/glowstone/util/library/LibraryManager.java
> +         * @param library an object representing a library
`a {@link Library} instance representing a library`

2018-01-13 19:41 UTC, aramperes approved these changes

2018-01-17 14:08 UTC, mastercoms approved these changes

2018-01-17 14:08 UTC, merged