Fixed TODO: "Is main hand always the correct slot?"
GlowstoneMC/Glowstone pull request #893
Opened 2018-03-31 04:23 UTC by fionera

This pull request removes the TODO in the Bow Item

Its now checked in which Hand the Bow is so he can be damaged

2018-03-31 04:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=893) <br/>All committers have signed the CLA.

2018-03-31 04:56 UTC, aramperes requested changes

2018-03-31 04:56 UTC, momothereal commented on src/main/java/net/glowstone/block/itemtype/ItemBow.java
> +            if (player.getItemInHand() == bow) {
The way Vanilla functionality works, you can predict in which slot the bow was in:

- If the item type of the main slot is `Material.BOW`, the main slot was used.
- Else, the off slot was used.

(The main slot takes priority, so even if the player has bows in both hands, you can expect that the one in the main hand was used).

This avoids the risk that the bow item is changed in the meantime, thus potentially breaking any equality check.

2018-05-21 14:03 UTC, mastercoms commented
Merged in https://github.com/GlowstoneMC/Glowstone/commit/db9e6718ee3ae8ef4c553569c29947ed430a0499, with the material check.

2018-05-21 14:03 UTC, closed without merging