Enhance Player Throw
GlowstoneMC/Glowstone pull request #901
Opened 2018-04-17 16:16 UTC by jordanmurray

This pull request attempts to solve the problem of a player not being able to throw an object with much velocity. The fix simply adds calculations to the initial velocity of the thrown object. The initial velocity is also randomized to match behavior on official server.

2018-04-17 16:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=901) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=901) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/Glowstone?pullRequest=901) it.</sub>

2018-04-17 17:13 UTC, momothereal commented
Hey, thank you for your contribution. May I ask where the values come from? Are they from trial-and-error?

2018-04-17 18:03 UTC, jordanmurray commented
Yes, the values come from a process of trial-and-error to find the closest similar behavior to the official server.

2018-04-19 04:06 UTC, Pr0methean requested changes

2018-04-19 04:06 UTC, Pr0methean commented on src/main/java/net/glowstone/entity/GlowHumanEntity.java
> +        double randOffset = 0.02;
Extract these constants to private static final fields.

2018-04-19 15:24 UTC, aramperes commented on src/main/java/net/glowstone/entity/GlowHumanEntity.java
> +        double randOffset = 0.02;
These values are approximate and have no real significance, I don't think constants are necessary. But it shouls have comments clarifying the calculations a bit.

2018-04-20 18:30 UTC, Pr0methean approved these changes

2018-04-20 18:31 UTC, merged