Fixed Explosions
GlowstoneMC/Glowstone pull request #969
Opened 2018-10-12 11:31 UTC by yehan2002

- Fixed explosion radius
-  Exclude players in creative mode and spectator mode from explosions

2018-10-12 11:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=969) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/Glowstone?pullRequest=969) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/Glowstone?pullRequest=969) it.</sub>

2018-10-12 21:24 UTC, Pr0methean requested changes

2018-10-12 21:24 UTC, Pr0methean commented on src/main/java/net/glowstone/Explosion.java
> +                    & player.getGameMode() != GameMode.SPECTATOR) {
Use a switch statement here. If `getGameMode()` ever becomes nontrivial, we'll want to call it only once, and a switch is more elegant than extracting into a variable.

2018-10-16 02:23 UTC, mastercoms commented
Why would we not send an explosion message to the client if they are in creative or spectator mode?

2018-12-15 11:16 UTC, mastercoms commented
Could you please address the above comment?

2018-12-17 09:56 UTC, closed without merging