#922 - Implement the PlayerLevelChangeEvent
GlowstoneMC/Glowstone pull request #983
Opened 2018-12-01 07:11 UTC by FlorentClarret

Contributes to issue #922

2018-12-01 22:26 UTC, Pr0methean requested changes

2018-12-01 22:26 UTC, Pr0methean commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +                    new PlayerLevelChangeEvent(this, this.level, newLevel));
Check if the returned event `isCancelled`.

2018-12-01 22:26 UTC, Pr0methean commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +                setLevel(level + 1);
This makes the XP bar empty even if the level-up was cancelled. Shouldn't it stay full in that case?

2018-12-02 06:15 UTC, FlorentClarret commented on src/main/java/net/glowstone/entity/GlowPlayer.java
> +                    new PlayerLevelChangeEvent(this, this.level, newLevel));
I might be wrong, but the `PlayerLevelChangeEvent` does not implement the `Cancellable` interface. So I can't check any `isCancelled` method.

2018-12-04 04:58 UTC, Pr0methean approved these changes

2018-12-05 04:31 UTC, mastercoms approved these changes

2018-12-05 04:31 UTC, merged