[WIP] RegionFile fixes and improvements
GlowstoneMC/Glowstone pull request #997
Opened 2018-12-28 11:38 UTC by astei

This is still a work in progress, but in short:

* Resolves chunk-writing issues.
* Fixes chunk header reading.
* Removes chunk timestamps since they are not used.

2018-12-28 20:54 UTC, Pr0methean approved these changes

2018-12-28 22:01 UTC, mastercoms requested changes

2018-12-28 22:01 UTC, mastercoms commented on src/main/java/net/glowstone/io/anvil/RegionFile.java
> -        // read timestamps from timestamp table
Although they are not used, they are part of the spec. Could you change usage of timestamps to be a configurable option?

2018-12-31 16:32 UTC, astei commented
I am still having issues with alignment, but the server is no longer crashing and persists changes to the world correctly. I will try to get some more time to finalize this soon.

2019-01-03 12:02 UTC, astei commented
Won't be available for the next three days. Will resolve your concerns by then.

2019-01-26 06:33 UTC, astei commented
Sorry for my late responses, college has kept me busy.

@mastercoms I readded timestamps.

2019-01-26 07:31 UTC, mastercoms commented
Is this still WIP?

2019-01-26 07:33 UTC, astei commented
There is still an unaligned error but worlds load and save changes correctly, and I'm not sure what's causing it. It might be macOS or something...

2019-01-26 07:34 UTC, mastercoms approved these changes

2019-01-26 07:35 UTC, mastercoms commented
Ok, in favor of at least fixing some errors, I'll merge.

2019-01-26 07:35 UTC, merged